#!/usr/bin/env bash

# exit when any command fails
set -e

function=$1
bucket=cosmostuna-backend
lambda_path=$COSMOS_TUNA_PATH/lambda
start_path=$(pwd)

cd "$lambda_path"
pwd

module_path="$(find . -type f -exec grep -l "module $function" {} \; | head -n 1)"
if [ -z "$module_path" ]; then
    echo "Failed to find module for $function"
    exit 1
else
    echo "Found lambda module at $module_path"
fi

build_path=$(dirname "$module_path")

cd "$build_path"
pwd

echo "Building Lambda function $function"
GOOS=linux go build

echo "Zipping Lambda function $function"
zip "$function.zip" "./$function"

s3_path="s3://$bucket/$function.zip"
echo "Uploading Lambda binary to $s3_path"

aws s3 cp "$function.zip" "$s3_path"

echo "Updating Lambda function"

aws lambda update-function-code\
    --function-name "$function" --s3-bucket "$bucket" --s3-key "$function.zip"

echo Cleaning up
rm "$function"
rm "$function.zip"
cd "$start_path"
