#!/usr/bin/env bash

FUNCTION=$1
BUCKET=cosmostuna-backend
PROJECT_PATH=$HOME/projects/comptcheshop
LAMBDA_PATH=$PROJECT_PATH/lambda/$FUNCTION/

echo Entering $LAMBDA_PATH
cd $LAMBDA_PATH

echo Building Lambda function $FUNCTION
GOOS=linux go build
if [ $? -eq 0 ]; then
    echo build ok
else
    echo build failed
    exit 1
fi

echo Zipping Lambda function $FUNCTION
zip $FUNCTION.zip ./$FUNCTION

echo Uploading Lambda binary to s3://$BUCKET/$FUNCTION.zip
aws s3 cp $LAMBDA_PATH/$FUNCTION.zip s3://$BUCKET/$FUNCTION.zip

echo Updating Lambda function
aws lambda update-function-code\
  --function-name $FUNCTION\
  --s3-bucket $BUCKET\
  --s3-key $FUNCTION.zip

echo Cleaning up
rm $FUNCTION
rm $FUNCTION.zip
cd -

