#!/usr/bin/env bash

aws s3 sync $HOME/projects/comptcheshop s3://cosmostuna.com \
--exclude "*" \
--include "*.html" \
--include "*.png" \
--include "*.jpg" \
--include "*.css" \
--include "*.js" \
--include "favicon.ico" \
$1

